In [10]:
# Import libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Read csv
dataset = pd.read_csv("Social_Network_Ads.csv")
#print(dataset)

dataset=pd.get_dummies(dataset,drop_first=True)
#dataset

dataset = dataset.drop("User ID",axis=1)
dataset["Purchased"].value_counts()

indep = dataset[["Age","EstimatedSalary","Gender_Male"]]
dep = dataset["Purchased"]

indep.shape
dep

# split into training and test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(indep, dep, test_size = 1/3, random_state = 0)

# Fit creates the model GaussianNB
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)
y_pred =classifier.predict(X_test)

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

# 6 is type I error  and  9 is type II error,
# type I error should be minimum, type II error does not have to be minimum value
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, y_pred)
print(clf_report)


# Fit creates the model MultinomialNB
from sklearn.naive_bayes import MultinomialNB
classifier = MultinomialNB()
classifier.fit(X_train, y_train)
y_pred =classifier.predict(X_test)

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

# 6 is type I error  and  9 is type II error,
# type I error should be minimum, type II error does not have to be minimum value
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, y_pred)
print(clf_report)

# Fit creates the model BernoulliNB
from sklearn.naive_bayes import BernoulliNB
classifier = BernoulliNB()
classifier.fit(X_train, y_train)
y_pred =classifier.predict(X_test)

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

# 6 is type I error  and  9 is type II error,
# type I error should be minimum, type II error does not have to be minimum value
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, y_pred)
print(clf_report)

# Fit creates the model CategoricalNB
from sklearn.naive_bayes import CategoricalNB
classifier = CategoricalNB()
classifier.fit(X_train, y_train)
y_pred =classifier.predict(X_test)

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

# 6 is type I error  and  9 is type II error,
# type I error should be minimum, type II error does not have to be minimum value
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, y_pred)
print(clf_report)

# Fit creates the model ComplementNB
from sklearn.naive_bayes import ComplementNB
classifier = ComplementNB()
classifier.fit(X_train, y_train)
y_pred =classifier.predict(X_test)

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

# 6 is type I error  and  9 is type II error,
# type I error should be minimum, type II error does not have to be minimum value
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, y_pred)
print(clf_report)

[[80  5]
 [ 8 41]]
              precision    recall  f1-score   support

           0       0.91      0.94      0.92        85
           1       0.89      0.84      0.86        49

    accuracy                           0.90       134
   macro avg       0.90      0.89      0.89       134
weighted avg       0.90      0.90      0.90       134

[[85  0]
 [49  0]]
              precision    recall  f1-score   support

           0       0.63      1.00      0.78        85
           1       0.00      0.00      0.00        49

    accuracy                           0.63       134
   macro avg       0.32      0.50      0.39       134
weighted avg       0.40      0.63      0.49       134

[[85  0]
 [49  0]]
              precision    recall  f1-score   support

           0       0.63      1.00      0.78        85
           1       0.00      0.00      0.00        49

    accuracy                           0.63       134
   macro avg       0.32      0.50      0.39       134
weighted avg     

/home/kumar/anaconda3/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/home/kumar/anaconda3/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/home/kumar/anaconda3/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/home/kumar/anac